config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'

  get '/home', to: 'pages#home'

  resources :recipes do
    member do
      post 'like'
    end
  end


end

app/models/chef.rb
class Chef < ActiveRecord::Base
  has_many :recipes
  has_many :likes
  before_save { self.email = email.downcase }
  validates :chefname, presence: true, length: {minimum: 5, maximum: 30}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: {maximum: 100},
                                    uniqueness: { case_sensitive: false},
                                    format: { with: VALID_EMAIL_REGEX }
end

app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :chef
  belongs_to :recipe

  validates_uniqueness_of :chef, scope: :recipe
end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
  belongs_to :chef
  has_many :likes
  validates :chef_id, presence: true
  validates :name, presence: true, length: {minimum: 5, maximum: 100}
  validates :summary, presence: true, length: {minimum: 10, maximum: 150}
  validates :description, presence: true, length: {minimum: 20, maximum: 200}
  mount_uploader :picture, PictureUploader
  validate :picture_size
  default_scope ->  { order(updated_at: :desc) }

  def thumbs_up_total
    self.likes.where(like: true).size
  end

  def thumbs_down_total
    self.likes.where(like: false).size
  end

  private
    def picture_size
      if picture.size > 6.megabytes
        errors.add(:picture, "Should be less than 6MB")
      end
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :find_recipes, only: [:show, :edit, :update, :destroy, :like]

  def index
    @recipes = Recipe.paginate(page: params[:page], per_page: 4)
  end

  def new
    @recipe = Recipe.new
  end

  def show
  end

  def create
    @recipe = Recipe.new(recipe_params)
    @recipe.chef = Chef.find(2)

    if @recipe.save
      flash[:success] = "Your recipe has been created successfully"
      redirect_to recipes_path

    else
      render :new
    end
  end

  def edit
  end

  def update
    if @recipe.update(recipe_params)
      flash[:success] = "Recipe updated successfully!"
      redirect_to recipe_path(@recipe)
    else
      render :edit
    end
  end

  def destroy
  end

  def like
    like = Like.create(like: params[:like], chef: Chef.second, recipe: @recipe)
    if like.valid?
      flash[:success] = "You have liked #{@recipe.name}"
      redirect_to :back
    else
      flash[:danger] = "You can only like/dislike a recipe once."
      redirect_to :back
    end
  end

  private

    def find_recipes
      @recipe = Recipe.find(params[:id])
    end

    def recipe_params
      params.require(:recipe).permit(:name, :summary, :description, :picture)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def gravatar_for(chef, options = {size: 80})
    gravatar_id = Digest::MD5::hexdigest(chef.email.downcase)
    size = options[:size]
    gravatar_url = "http://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: chef.chefname, class: "gravatar")
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_footer.html.slim
.footer 
  p &copy; BearCave Studios 2015

app/views/layouts/_messages.html.slim
.row
  .col-md-10.col-md-offset-1
    - flash.each do |message_type, message|
      div class=["alert", "alert-#{message_type}", "center"]
        | #{message}
        a.close data-dismiss="alert"
          | &#215;

app/views/layouts/_nav.html.slim
header
  nav.navbar.navbar-fixed-top.navbar-default
    .container
      = link_to 'myRecipes', root_path, class: 'btn btn-lg btn-success', id: 'logo'

      .nav-item
        = link_to 'link 1', '', class: 'btn btn-default btn-warning'
        = link_to 'link 2', '', class: 'btn btn-default btn-warning'
        = link_to 'New Recipe', new_recipe_path, class: 'btn btn-default btn-warning'

app/views/layouts/application.html.slim
doctype html
html
  head
    title Recipemanager
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags

  body

  == render 'layouts/nav'
  .container
    == render 'layouts/messages'
    == yield
  == render 'layouts/footer'

app/views/pages/home.html.slim
.jumbotron.center
  h1 Welcome to MyRecipes App

  h2 This is the home page for the Profressional Ruby on Rails Course.

  = link_to 'Sign up now!', '', class: 'btn btn-lg btn-success'

.row
  .col-lg-4
    h3.midrow View Recipes as Guest User
    h2.left Brows and view recipes as guest and sign up later
    = link_to 'Browse Recipe Listings', recipes_path, class: 'btn btn-warning btn-small'

  .col-lg-4
    h3.midrow View Recipes as Guest User
    h2.left Brows and view recipes as guest and sign up later
    = link_to 'Browse Recipe Listings', '', class: 'btn btn-warning btn-small'

  .col-lg-4
    h3.midrow View Recipes as Guest User
    h2.left Brows and view recipes as guest and sign up later
    = link_to 'Browse Recipe Listings', '', class: 'btn btn-warning btn-small'

app/views/recipes/_form.html.slim
== render 'shared/errors', obj: @recipe
.row
  .col-md-8.col-md-offset-2.well
    = simple_form_for(@recipe, html: { multipart: true}) do |f|
      .form-group
        = f.input :name, class: 'form-control'
      .form-group
        = f.input :summary, class: 'form-control'
      .form-group
        = f.input :description, input_html: {rows: 10}, class: 'form-control'
      .form-group
        span.picture
          = f.file_field :picture, accept: 'image/jpeg, image/png, image/gif,'
      .form-group
        = f.submit(@recipe.new_record? ? 'Create Recipe' : 'Edit Recipe', class: "btn btn-success form-control form-button")


      javascript:
        $('#recipe_picture').bind('change', function() {
          size_in_megabytes = this.files[0].size/1024/1024;
          if (size_in_megabytes > 6) {
            alert('Maximum file size is 6MB. Please choose a smaller file.');
          }
        });

app/views/recipes/edit.html.slim
== render 'shared/page_title', title: 'Edit Recipe'

== render 'form'

app/views/recipes/index.html.slim
== render 'shared/page_title', title: 'All Recipes'
hr
.center
  = will_paginate

- @recipes.each do |recipe|
  .row
    .col-md-2
      section.chef_info.center
        = gravatar_for recipe.chef, size: 100
        h5 Chef Name: #{recipe.chef.chefname}
    .col-lg-6.well
      h4.recipe_title
        = link_to recipe.name, recipe
        p
          = recipe.summary
        p
          span.quiet
            small
               | Created #{time_ago_in_words(recipe.created_at)} ago, &nbsp
          span.quiet
            small
              | Updated #{time_ago_in_words(recipe.updated_at)} ago
        .button-group
          = link_to like_recipe_path(recipe, like: true), class: 'btn btn-sm btn-default', method: :post do
            i.glyphicon.glyphicon-thumbs-up
            = recipe.thumbs_up_total

          = link_to like_recipe_path(recipe, like: false), class: 'btn btn-sm btn-default', method: :post do
            i.glyphicon.glyphicon-thumbs-down
            = recipe.thumbs_down_total
    .col-md-4
      = image_tag(recipe.picture.url, size: "250x150", class: "gravatar") if recipe.picture?
  hr

.center
  = will_paginate


app/views/recipes/new.html.slim
== render 'shared/page_title', title: 'New Recipe'

== render 'form'

app/views/recipes/show.html.slim
== render 'shared/page_title', title: @recipe.name

.row
  .col-md-4.pull-right.center
    = gravatar_for @recipe.chef, size: 200
    p
      h5 Brought to you by: #{@recipe.chef.chefname}

  .col-md-8
    = link_to 'Edit Recipe', edit_recipe_path, class: 'btn btn-sm btn-success pull-right'
    h3 = @recipe.summary
    .show_recipe
      = image_tag(@recipe.picture.url) if @recipe.picture?
    .well
      p
        strong Steps:
      = simple_format(@recipe.description)
      .button-group.center
        = link_to like_recipe_path(like: true), class: 'btn btn-sm btn-default', method: :post do
          i.glyphicon.glyphicon-thumbs-up
          = @recipe.thumbs_up_total

        = link_to like_recipe_path(like: false), class: 'btn btn-sm btn-default', method: :post do
          i.glyphicon.glyphicon-thumbs-down
          = @recipe.thumbs_down_total



.row
  .col-md-6
    = link_to "Back", recipes_path, class: "btn btn-sm btn-primary"

app/views/shared/_errors.html.slim
- if obj.errors.any?
  .row
    .alert.alert-danger.col-md-8.col-md-offset-2
      h5 Please correct the following errors
      ul
       = obj.errors.full_messages.each do |msg|
        li = msg

app/views/shared/_page_title.html.slim
p
  h1 #{title}